//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int id { get; set; }
        public Nullable<int> title_id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string surname { get; set; }
        public bool gender_type { get; set; }
        public int material_id { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public Nullable<int> state_of_origin_id { get; set; }
        public string tribe { get; set; }
        public int religion_id { get; set; }
        public int occupation_id { get; set; }
        public string permanent_adress { get; set; }
        public string home_adress { get; set; }
        public string photo { get; set; }
        public int family_id { get; set; }
        public string old_file_number { get; set; }
        public int card_type_id { get; set; }
        public int patient_category_id { get; set; }
        public Nullable<int> existing_account_id { get; set; }
        public int account_number { get; set; }
    
        public virtual Card_Type Card_Type { get; set; }
        public virtual Existing_Account Existing_Account { get; set; }
        public virtual Material_Status Material_Status { get; set; }
        public virtual Occupation Occupation { get; set; }
        public virtual Patient Patient1 { get; set; }
        public virtual Patient Patient2 { get; set; }
        public virtual Patient_Category Patient_Category { get; set; }
        public virtual Patient_Family Patient_Family { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual State_of_Origin State_of_Origin { get; set; }
        public virtual Title Title { get; set; }
    }
}
